### ISSUE TITLE
error when opening jupyter

### ISSUE THREAD

**Issue by kaiwenShen** [hacksoc-manchester/coding-classes#1]
Fatal Python error: init_sys_streams: can't initialize sys standard streams
LookupError: unknown encoding: 65001

Current thread 0x000036bc (most recent call first):

running jupyter on anacoda on windows system

**Comment by achadha0111** [comment]
This link should help solve the issue - https://stackoverflow.com/questions/51053464/fatal-python-error-py-initialize-cant-initialize-sys-standard-streams-lookupe

You can change system encoding by following this - https://i.stack.imgur.com/50MXn.png
